MOBILEAPPS-1952: Added External SSO flow to obtain an AcsApiClient
foreseecode/acs-apiclient-net pull request #6
Opened 2017-12-18 18:02 UTC by ahmadhusseini

2017-12-20 01:14 UTC, sleeke requested changes
⚠️ This looks great in general, but there's a bunch of suggestions here for readability, clarity, etc., and some we should chat about another day 🙂

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/AcsApiClient.cs
> +                !config.IsSSOClient
:bowtie: The newline seems a little strange here

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        InvalidCode,
💡 It might be worth being more specific to avoid future conflicts, e.g ```IdpCodeInvalid```

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        StateMismatch,
💡 Same here, maybe ```IdpStateMismatch```

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        Interrupted,
💡 In the vein of being specific (as mentioned in the comments below), maybe this should be ```InterruptedByUser```?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        ClientError,
❓ Is it worth differentiating between ClientError and BadRequest? Technically they're both Client Errors

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidCancelLoginProcess();
💡 Again, maybe the more specific ```UserCancelledLogin``` would be better

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidRetrieveCodeSuccessfully();
💡 The use of ```DidDoSomething``` is very iOS-centric. Perhaps ```RetrievedCode``` would be better?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidEncounterError(AcsApiError error);
💡 As above; maybe ```LoginFailedWithError```

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidEncounterError(AcsApiError error);
...or perhaps something more specific if this isn't for the entire login process

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginDelegate.cs
> +        void ShouldBeginPasswordFlow();
💡 I wonder if this should be called ```BeginNonSsoFlow```?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginDelegate.cs
> +        void ShouldBeginPasswordFlow();
or ```BeginLocalFlow```?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +        void BeginAccessTokenExchange(string code)
💡 Let's be specific about this; which token are we exchanging. To my mind, it could be:
 - OAuth1
 - OKTA

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +            acsApiClientConfiguration.AccessTokenSecret = oauthSecret;
💡 I think that now we're dealing with so many access tokens, keys and secrets, it would be worth being specific about which is which. Here, in the clientConfiguration, I think that the name OAuthToken and OAuthSecret would be better than AccessToken and AccessTokenSecret

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                RunOnMainThread(() => loginDelegate.DidEncounterError(AcsApiError.CouldNotLogin));
❓ Could we add some more detail to this response? It seems like this could be for any number of reasons, and it'd be helpful to pass some info along...

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                throw new AcsApiException(AcsApiError.InvalidCode);
❓ Is it worth differentiating between an empty state and an invalid code?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                throw new AcsApiException(AcsApiError.InvalidCode);
maybe this is more accurately an ```invalidRedirectParameters```?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidRetrieveCodeSuccessfully();
or maybe ```continueTokenExchange```

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/Models/IdentityProvider.cs
> +                var parameterString = string.Join("&", encodedParameters);
❓ I wonder if it's worth pulling the formation of this string out to a utility method for readability's sake, if not for future convenience?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/PlatformLoginController.cs
> +        /// <param name="context">The context from which the external flow will launch from.</param>
:bowtie: Should be "The context from which the external flow will launch"

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/PlatformLoginController.cs
> +        protected abstract void RunOnMainThread(Action action);
❓ Should this be pulled out to a separate threading interface?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/iOS/ExternalFlowWebViewController.cs
> +            dismissButton = new UIBarButtonItem(closeIcon, UIBarButtonItemStyle.Plain, (sender, e) =>
⚠️ The close and refresh icons don't look like they fit with each other. Since you've used the system's refresh button, perhaps we should also use the system's cancel (```UIBarButtonSystemItem.Stop```) button?

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/iOS/ExternalFlowWebViewController.cs
> +            PrepareWebView();
👍 Nice tidy prepare function, I like the style 🙂

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/iOS/LoginController.iOS.cs
> +                throw new NotImplementedException(
:bowtie: Should be an ```ArgumentException```

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/AcsApiClient.cs
> +                !config.IsSSOClient
I think we need to come up with a convention... 🤔

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                RunOnMainThread(() => loginDelegate.DidEncounterError(AcsApiError.CouldNotLogin));
I guess this is tricky since we only pass back an enum, but maybe it's worth passing more back? Let's chat about it

2017-12-20 01:14 UTC, sleeke commented on acs-apiclient/iOS/ExternalFlowWebViewController.cs
> +        ) {
:bowtie: We need to come unp with  convention here. I'm definitely more of a fan of keeping brackets on the same line as the final argument:
```
        public void DecidePolicy(
            WKWebView webView,
            WKNavigationAction navigationAction,
            Action<WKNavigationActionPolicy> decisionHandler) 
        {
            try
```

But also willing to bow to C# conventions or you guys' preference...

2017-12-20 23:31 UTC, ahmadhusseini commented on acs-apiclient/iOS/LoginController.iOS.cs
> +                throw new NotImplementedException(
👍

2017-12-20 23:35 UTC, ahmadhusseini commented on acs-apiclient/iOS/ExternalFlowWebViewController.cs
> +            dismissButton = new UIBarButtonItem(closeIcon, UIBarButtonItemStyle.Plain, (sender, e) =>
Changed the refresh button to match the designs.

2017-12-20 23:36 UTC, ahmadhusseini commented on acs-apiclient/PlatformLoginController.cs
> +        /// <param name="context">The context from which the external flow will launch from.</param>
👍

2017-12-21 00:27 UTC, ahmadhusseini commented on acs-apiclient/Models/IdentityProvider.cs
> +                var parameterString = string.Join("&", encodedParameters);
👍

2017-12-21 00:27 UTC, ahmadhusseini commented on acs-apiclient/LoginController.cs
> +                throw new AcsApiException(AcsApiError.InvalidCode);
👍

2017-12-21 00:27 UTC, ahmadhusseini commented on acs-apiclient/LoginController.cs
> +                RunOnMainThread(() => loginDelegate.DidEncounterError(AcsApiError.CouldNotLogin));
👍

2017-12-21 00:30 UTC, ahmadhusseini commented on acs-apiclient/LoginController.cs
> +            acsApiClientConfiguration.AccessTokenSecret = oauthSecret;
👍

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiClient.cs
> -                && (string.IsNullOrEmpty(config.PortalPassword) || string.IsNullOrEmpty(config.PortalUsername))
❓ Look into the conventions here

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiClientConfig.cs
> +        /// A token received upon authenticating
💡 "A token received upon completing the entire login process. This will be used for access to the ForeSee services"

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiClientConfig.cs
> +        /// A secret received upon authenticating
💡 "A token received upon completing the entire login process. Used in conjunction with the OAuthToken"

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                RunOnMainThread(() => loginDelegate.EncounteredError(AcsApiError.Other, exception.Message));
❓ Where is the ```other``` type used?

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                loginDelegate.EncounteredError(AcsApiError.InvalidCallbackParameters, "The Auth Code is invalid.");
💡 "The retrieved Auth Code is invalid"

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +        public void EncounteredError(AcsApiError error, string message, string code = "")
❓ Is there a reason this isn't passed as a number?

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/iOS/ExternalFlowWebViewController.cs
> +				webView.LoadRequest(new NSUrlRequest(urlToLoad));
⚠️ This seems to be the opposite of what I suggested. Check out how it looks

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiClient.cs
> +                !config.IsSSOClient
✅

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        Interrupted,
✅

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        InvalidCode,
✅

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        StateMismatch,
✅

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/AcsApiError.cs
> +        ClientError,
✅

2017-12-21 18:21 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidCancelLoginProcess();
✅

2017-12-21 18:22 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidRetrieveCodeSuccessfully();
✅

2017-12-21 18:22 UTC, sleeke commented on acs-apiclient/ExternalFlowDelegate.cs
> +        void DidEncounterError(AcsApiError error);
✅

2017-12-21 18:22 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +        void BeginAccessTokenExchange(string code)
✅

2017-12-21 18:22 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +            acsApiClientConfiguration.AccessTokenSecret = oauthSecret;
✅

2017-12-21 18:22 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                RunOnMainThread(() => loginDelegate.DidEncounterError(AcsApiError.CouldNotLogin));
✅

2017-12-21 18:24 UTC, sleeke commented on acs-apiclient/LoginController.cs
> +                throw new AcsApiException(AcsApiError.InvalidCode);
✅

2017-12-21 18:25 UTC, sleeke commented on acs-apiclient/Models/IdentityProvider.cs
> +                var parameterString = string.Join("&", encodedParameters);
✅

2017-12-21 18:25 UTC, sleeke commented on acs-apiclient/PlatformLoginController.cs
> +        /// <param name="context">The context from which the external flow will launch from.</param>
✅

2017-12-21 18:26 UTC, sleeke commented on acs-apiclient/iOS/ExternalFlowWebViewController.cs
> +        ) {
✅

2017-12-21 18:26 UTC, sleeke commented on acs-apiclient/iOS/LoginController.iOS.cs
> +                throw new NotImplementedException(
✅

2017-12-22 17:30 UTC, merged